# config/routes.yaml

accueil:
  path: /
  controller: App\Controller\AccueilController::accueil


connexion:
  path: /connexion
  methods: GET|HEAD|POST
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: security/connexion.html.twig
deconnexion:
  path: /deconnexion
  methods: GET

inscription:
  path: /inscription
  methods: GET|HEAD
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: security/inscription.html.twig
inscription-post:
  path: /inscription
  methods: POST
  controller: App\Controller\SecurityController::inscription
testForm:
  path: /test
  controller: App\Controller\SecurityController::testForm



quiz:
  path: /quiz
  controller: App\Controller\QuizController::quiz
