# config/routes.yaml

accueil:
  path: /
  controller: App\Controller\AccueilController::accueil

aPropos:
  path: /aPropos
  controller: App\Controller\AccueilController::aPropos

# Security
connexion:
  path: /connexion
  methods: GET|HEAD|POST
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: security/connexion.html.twig
deconnexion:
  path: /deconnexion
  methods: GET
inscription:
  path: /inscription
  methods: GET|HEAD|POST
  controller: App\Controller\SecurityController::inscription


# Admin
admin:
  path: /admin/
  controller: App\Controller\AdminController::index

# Main site
quiz:
  path: /quiz
  controller: App\Controller\QuizController::quiz
  methods: GET|HEAD

play:
  path: /quiz/{id}/play
  controller: App\Controller\QuizController::play
  methods: GET|HEAD

ajouter-question:
  path: /quiz/{id}/ajouter-question
  controller: App\Controller\QuizController::ajouterQuestion

valider-question:
  path: /validationQuestion
  controller: App\Controller\QuizController::validerQuestion
  methods: POST

profile:
  path: /profile
  controller: App\Controller\ProfileController::index
  methods: GET|HEAD
