# config/routes.yaml

accueil:
  path: /
  controller: App\Controller\AccueilController::accueil


connexion:
  path: /connexion
  methods: GET|HEAD|POST
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: security/connexion.html.twig
deconnexion:
  path: /deconnexion
  methods: GET
inscription:
  path: /inscription
  methods: GET|HEAD|POST
  controller: App\Controller\SecurityController::inscription


quiz:
  path: /quiz
  controller: App\Controller\QuizController::quiz

play:
  path: /{id}/play
  controller: App\Controller\QuizController::play

ajouter-question:
  path: /{id}/ajouter-question
  controller: App\Controller\QuizController::ajouterQuestion

valider-question:
  path: /validationQuestion
  controller: App\Controller\QuizController::validerQuestion
  methods: POST
