# config/routes.yaml

accueil:
  path: /
  controller: App\Controller\AccueilController::accueil


connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::connexion

inscription:
  path: /inscription
  controller: App\Controller\InscriptionController::inscription


quiz:
  path: /quiz
  controller: App\Controller\QuizController::quiz